### ISSUE TITLE
notify-resource-deployment-status-change results in an internal server error 

### ISSUE THREAD

**Issue by RichardChester** [aws-containers/proton-codebuild-provisioning-examples#42]
When I run:
`aws proton notify-resource-deployment-status-change --resource-arn $RESOURCE_ARN --outputs file://./outputs.json`

It results in an internal server error (500), I've checked the arn and even tried simplifying it by removing --outputs still doesn't work

@rafavallina

**Comment by vttrmv-prod** [comment]
Hey RichardChester, it looks like we have a validation bug on our end when using cross account environments, let me know if this sounds like your use case (?). We're working on a fix on our end but the internal server error is very likely a permission issue we're not handling properly on our side. I will post an update when the fix is deployed.

**Comment by ghost** [comment]
Hey RichardChester, it looks like we have a validation bug on our end when using cross account environments, let me know if this sounds like your use case (?). We're working on a fix on our end but the internal server error is very likely a permission issue we're not handling properly on our side. I will post an update when the fix is deployed.

**Comment by RichardChester** [comment]
Hello nouvionp, yes that is exactly my use case. That being said I had a similar issue when trying to run the command local on my own machine which has Admin on the proton account and got the same error. To repeat I basically ran the script in code build exactly as it is shown in the examples for this repo but instead of trying to run  

`aws proton notify-resource-deployment-status-change --resource-arn $RESOURCE_ARN --outputs file://./outputs.json`

from code build I removed it, put in a 5 min sleep and tried to run it local when it got to the sleep but got the exact same internal server error

**Comment by ghost** [comment]
K it looks like our fix was fully deployed, let me know if you are still running into issues and I will have my team dig into this more.

**Comment by RichardChester** [comment]
Yea that looks like it's worked perfectly, thanks @nouvionp & the proton team
